name: Deploy Django to EC2
on: #prueba de activación
  push:
    branches:
      - Master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Crear carpeta en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Creamos la carpeta donde estará todo el proyecto
            # Esto debe ser la ruta final donde quieres los archivos de tu proyecto
            mkdir -p /home/ubuntu/modulo-8-contabilidad

      - name: Subir código a EC2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avz --delete"
         
          path: "./" 
          remote_host: ${{ secrets.IP_SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_path: "/home/ubuntu/modulo-8-contabilidad/" 
          remote_key: ${{ secrets.PRIVATE_KEY }}
          remote_port: ${{ secrets.PORT }}

      - name: Crear archivo .env en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # El .env se creará ahora dentro de la carpeta del proyecto
            cat <<EOF > /home/ubuntu/modulo-8-contabilidad/.env
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            DJANGO_DEBUG=True
            MYSQL_DATABASE=BdContabilidad
            MYSQL_USER=USUARIOOCHO
            MYSQL_PASSWORD=admin
            MYSQL_HOST=db
            MYSQL_PORT=3306
            EOF

      - name: Levantar contenedores con Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navegamos a la carpeta donde ahora está docker-compose.yml
            cd /home/ubuntu/modulo-8-contabilidad 
            docker compose down
            docker compose up -d --build

      - name: Ejecutar migraciones de Django
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navegamos a la carpeta donde ahora está docker-compose.yml
            cd /home/ubuntu/modulo-8-contabilidad
            docker-compose exec backend python manage.py migrate
