# Generated by Django 5.2 on 2025-05-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsiento', models.DateField()),
                ('descripcionAsiento', models.TextField()),
                ('referenciaAsiento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCuenta', models.CharField(max_length=500)),
                ('tipoCuenta', models.CharField(max_length=500)),
                ('codigoCuenta', models.CharField(max_length=600)),
                ('descripcionCuenta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContabilidad.asientocontable')),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContabilidad.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTransaccion', models.CharField(max_length=500)),
                ('montoTransaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaTransaccion', models.DateField()),
                ('idAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContabilidad.asientocontable')),
            ],
        ),
    ]
