# Generated by Django 5.2.1 on 2025-05-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cuentacontable',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalleasiento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'managed': False},
        ),
    ]
