# Generated by Django 5.2.1 on 2025-05-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContabilidad', '0002_alter_asientocontable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asientocontable',
            table='AsientoContable',
        ),
        migrations.AlterModelTable(
            name='cuentacontable',
            table='CuentaContable',
        ),
        migrations.AlterModelTable(
            name='detalleasiento',
            table='DetalleAsiento',
        ),
        migrations.AlterModelTable(
            name='transaccion',
            table='Transaccion',
        ),
    ]
