# Generated by Django 5.2.1 on 2025-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContabilidad', '0003_alter_asientocontable_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombreReporte', models.CharField(db_column='nombreReporte', max_length=500)),
                ('descripcionReporte', models.TextField(db_column='descripcionReporte')),
                ('fechaCreacion', models.DateField(db_column='fechaCreacion')),
                ('tipoReporte', models.CharField(db_column='tipoReporte', max_length=200)),
            ],
            options={
                'db_table': 'Reporte',
                'managed': False,
            },
        ),
    ]
