# Generated by Django 5.2.1 on 2025-05-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContabilidad', '0004_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteContable',
            fields=[
                ('idReporte', models.AutoField(db_column='idReporte', primary_key=True, serialize=False)),
                ('archivoReporte', models.TextField(blank=True, db_column='archivoReporte', null=True)),
                ('creacionReporte', models.DateTimeField(blank=True, db_column='creacionReporte', null=True)),
            ],
            options={
                'db_table': 'ReporteContable',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
